/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package conversor.de.monedas;

import RSMaterialComponent.RSTextFieldMaterialIcon;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
//import static conversor.de.monedas.Conversordetemperatura.getCbunidadentrada;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import rojerusan.RSComboBox;

/**
 *
 * @author santiago
 */
public class Conversordetemperatura extends javax.swing.JFrame {

    /**
     * Creates new form Convertidor
     */
    public Conversordetemperatura() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    public boolean esDecimal(String cad) {
        try {
            Double.valueOf(cad);
            return true;
        } catch (NumberFormatException nfe) {
            return false;
        }
    }

    public boolean validarcampos(int cb1, int cb2) {
        // try {
        if (cb1 != 0 && cb2 != 0) {
            return true;
        } else {
            JOptionPane.showMessageDialog(rootPane, "!selecione la moneda a convertir");
           this.setTxtunidadentrada("1");
           this.setTxtunidadsalida("1");
             this.txtunidadentrada.setForeground(Color.ORANGE);
             this.txtunidadsalida.setForeground(Color.ORANGE);
            return false;
        }

        //   } catch (NumberFormatException nfe) {
        //    }
        //return false;
    }

    private void cbprimero() {

        conversorTemperaturasmetodos ct = new conversorTemperaturasmetodos();

        if (esDecimal(this.getTxtunidadentrada())) {

            if (this.validarcampos(this.getCbunidadentrada(), this.getCbunidadsalida())) {

                //  } else {
                switch (getCbunidadentrada()) {

                    case 1 ->
                        this.setTxtunidadsalida(ct.conversorCENTIGRADOSsaTODOS(this.getTxtunidadentrada(), this.getCbunidadsalida()));
                    case 2 ->
                        this.setTxtunidadsalida(ct.conversorFAHRENHEITaTODOS(this.getTxtunidadentrada(), this.getCbunidadsalida()));
                    case 3 ->
                        this.setTxtunidadsalida(ct.conversorKELVINaTODOS(this.getTxtunidadentrada(), this.getCbunidadsalida()));
                    case 4 ->
                        this.setTxtunidadsalida(ct.conversorRANKINEaTODOS(this.getTxtunidadentrada(), this.getCbunidadsalida()));
                    case 5 ->
                        this.setTxtunidadsalida(ct.conversorREAUMURaTODOS(this.getTxtunidadentrada(), this.getCbunidadsalida()));
                        }

            }

        } else {

            JOptionPane.showMessageDialog(rootPane, "!el valor ingresado no es valido");
            this.txtunidadentrada.setText("1");

        }
    }

    private void cbsegundo() {

        conversorTemperaturasmetodos ct = new conversorTemperaturasmetodos();

        if (esDecimal(this.getTxtunidadsalida())) {

            if (this.validarcampos(this.getCbunidadentrada(),this.getCbunidadsalida())) {
                
                   switch (getCbunidadsalida()) {

                    case 1 ->
                       this.setTxtunidadentrada(ct.conversorCENTIGRADOSsaTODOS(this.getTxtunidadsalida(), this.getCbunidadentrada()));
                    case 2 ->
                        this.setTxtunidadentrada(ct.conversorFAHRENHEITaTODOS(this.getTxtunidadsalida(), this.getCbunidadentrada()));
                    case 3 ->
                        this.setTxtunidadentrada(ct.conversorKELVINaTODOS(this.getTxtunidadsalida(), this.getCbunidadentrada()));
                    case 4 ->
                        this.setTxtunidadentrada(ct.conversorRANKINEaTODOS(this.getTxtunidadsalida(), this.getCbunidadentrada()));
                    case 5 ->
                        this.setTxtunidadentrada(ct.conversorREAUMURaTODOS(this.getTxtunidadsalida(), this.getCbunidadentrada()));
              }
                
                
                
              
            } 

        } else {

            JOptionPane.showMessageDialog(rootPane, "!el valor ingresado no es valido");
            this.txtunidadsalida.setText("1");

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rSButtonIconUno1 = new RSMaterialComponent.RSButtonIconUno();
        cbunidadentrada = new rojerusan.RSComboBox();
        txtunidadentrada = new RSMaterialComponent.RSTextFieldMaterialIcon();
        cbunidadsalida = new rojerusan.RSComboBox();
        txtunidadsalida = new RSMaterialComponent.RSTextFieldMaterialIcon();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 204, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CONVERTIDOR DE MONEDAS");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 310, 30));

        rSButtonIconUno1.setBackground(new java.awt.Color(255, 204, 51));
        rSButtonIconUno1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLOSE);
        rSButtonIconUno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconUno1ActionPerformed(evt);
            }
        });
        jPanel2.add(rSButtonIconUno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 50, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 50));

        cbunidadentrada.setBackground(new java.awt.Color(255, 204, 51));
        cbunidadentrada.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ELIJA UNIDAD", "Centigrados °C", "Fahrenheit °F", "Kelvin K", "Rankine °R", "Réaumur °Re" }));
        cbunidadentrada.setColorArrow(new java.awt.Color(255, 204, 51));
        cbunidadentrada.setColorBorde(new java.awt.Color(255, 255, 0));
        cbunidadentrada.setColorFondo(new java.awt.Color(255, 204, 51));
        cbunidadentrada.setColorSeleccion(new java.awt.Color(255, 204, 51));
        cbunidadentrada.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbunidadentradaItemStateChanged(evt);
            }
        });
        cbunidadentrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbunidadentradaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbunidadentradaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cbunidadentradaMouseReleased(evt);
            }
        });
        jPanel1.add(cbunidadentrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 40));

        txtunidadentrada.setForeground(new java.awt.Color(255, 204, 51));
        txtunidadentrada.setText("1");
        txtunidadentrada.setColorIcon(new java.awt.Color(255, 204, 51));
        txtunidadentrada.setColorMaterial(new java.awt.Color(255, 204, 51));
        txtunidadentrada.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.MONETIZATION_ON);
        txtunidadentrada.setPhColor(new java.awt.Color(0, 0, 0));
        txtunidadentrada.setPlaceholder("Escribir aqui");
        txtunidadentrada.setSelectionColor(new java.awt.Color(255, 204, 51));
        txtunidadentrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtunidadentradaMouseReleased(evt);
            }
        });
        txtunidadentrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtunidadentradaActionPerformed(evt);
            }
        });
        txtunidadentrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtunidadentradaKeyReleased(evt);
            }
        });
        jPanel1.add(txtunidadentrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 190, -1));

        cbunidadsalida.setBackground(new java.awt.Color(255, 204, 51));
        cbunidadsalida.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ELIJA UNIDAD", "Centigrados °C", "Fahrenheit °F", "Kelvin K", "Rankine °R", "Réaumur °Re" }));
        cbunidadsalida.setColorArrow(new java.awt.Color(255, 204, 51));
        cbunidadsalida.setColorBorde(new java.awt.Color(255, 255, 0));
        cbunidadsalida.setColorFondo(new java.awt.Color(255, 204, 51));
        cbunidadsalida.setColorSeleccion(new java.awt.Color(255, 204, 51));
        cbunidadsalida.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbunidadsalidaItemStateChanged(evt);
            }
        });
        cbunidadsalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbunidadsalidaMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cbunidadsalidaMouseReleased(evt);
            }
        });
        jPanel1.add(cbunidadsalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, 40));

        txtunidadsalida.setForeground(new java.awt.Color(255, 204, 51));
        txtunidadsalida.setText("1");
        txtunidadsalida.setToolTipText("");
        txtunidadsalida.setColorIcon(new java.awt.Color(255, 204, 51));
        txtunidadsalida.setColorMaterial(new java.awt.Color(255, 204, 51));
        txtunidadsalida.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.MONETIZATION_ON);
        txtunidadsalida.setPhColor(new java.awt.Color(0, 0, 0));
        txtunidadsalida.setPlaceholder("Escribir aqui");
        txtunidadsalida.setSelectionColor(new java.awt.Color(255, 204, 51));
        txtunidadsalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtunidadsalidaMouseReleased(evt);
            }
        });
        txtunidadsalida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtunidadsalidaKeyReleased(evt);
            }
        });
        jPanel1.add(txtunidadsalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 190, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtunidadentradaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtunidadentradaKeyReleased

        // this.cbmonedaentrada.addActionListener((ActionEvent e) -> {
        cbprimero();


    }//GEN-LAST:event_txtunidadentradaKeyReleased

    private void txtunidadentradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtunidadentradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtunidadentradaActionPerformed

    private void txtunidadsalidaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtunidadsalidaKeyReleased

        cbsegundo();


    }//GEN-LAST:event_txtunidadsalidaKeyReleased

    private void cbunidadentradaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbunidadentradaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbunidadentradaMousePressed

    private void cbunidadsalidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbunidadsalidaMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_cbunidadsalidaMouseClicked

    private void cbunidadentradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbunidadentradaMouseClicked


    }//GEN-LAST:event_cbunidadentradaMouseClicked

    private void rSButtonIconUno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconUno1ActionPerformed
        // TODO add your handling code here:

        int resp = JOptionPane.showConfirmDialog(null, "DESEAS CERRAR EL CONVERSOR DE TEMPERATURA",
                "AVISO", JOptionPane.YES_NO_OPTION,
                JOptionPane.INFORMATION_MESSAGE);
        switch (resp) {
            case 0 -> this.dispose();
            case 1 -> {
            }

        }


    }//GEN-LAST:event_rSButtonIconUno1ActionPerformed

    private void txtunidadentradaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtunidadentradaMouseReleased
        // TODO add your handling code here:
        
        
        
        if (this.txtunidadentrada.getForeground() == Color.red) {
            cbprimero();

        } else {
            this.txtunidadentrada.setText("1");
            this.txtunidadentrada.setForeground(Color.red);
            this.txtunidadsalida.setForeground(Color.ORANGE);
            // this.txtmonedaentrada.setText("1");
            cbprimero();
        }


    }//GEN-LAST:event_txtunidadentradaMouseReleased

    private void txtunidadsalidaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtunidadsalidaMouseReleased
        // TODO add your handling code here:

        if (this.txtunidadsalida.getForeground() == Color.red) {
            cbsegundo();

        } else {
            this.txtunidadsalida.setText("1");
            this.txtunidadsalida.setForeground(Color.red);
            this.txtunidadentrada.setForeground(Color.ORANGE);
            // this.txtmonedaentrada.setText("1");
            cbsegundo();
        }


    }//GEN-LAST:event_txtunidadsalidaMouseReleased

    private void cbunidadentradaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbunidadentradaMouseReleased
        // TODO add your handling code here:
        //  cbprimero(); 

    }//GEN-LAST:event_cbunidadentradaMouseReleased

    private void cbunidadsalidaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbunidadsalidaMouseReleased
        // TODO add your handling code here:
        // if(  this.txtmonedaentrada.getForeground()==Color.red){
        //     this.txtmonedaentrada.setForeground(Color.ORANGE);
        //     }
        // cbsegundo();
    }//GEN-LAST:event_cbunidadsalidaMouseReleased


    private void cbunidadentradaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbunidadentradaItemStateChanged
        // TODO add your handling code here:

        if (evt.getSource() == this.cbunidadentrada) {

            if (this.txtunidadentrada.getForeground() == Color.red) {
                cbprimero();
            }
            if (this.txtunidadsalida.getForeground() == Color.red) {
                cbsegundo();
            }

            //   cbprimero(); 
        }


    }//GEN-LAST:event_cbunidadentradaItemStateChanged

    private void cbunidadsalidaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbunidadsalidaItemStateChanged
        // TODO add your handling code here:

        if (evt.getSource() == this.cbunidadsalida) {

            if (this.txtunidadentrada.getForeground() == Color.red) {
                cbprimero();
            }
            if (this.txtunidadsalida.getForeground() == Color.red) {
                cbsegundo();
            }

            //   cbprimero(); 
        }

    }//GEN-LAST:event_cbunidadsalidaItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Conversordetemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Conversordetemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Conversordetemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Conversordetemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Conversordetemperatura().setVisible(true);
        });
    }

    public String getTxtunidadentrada() {
        return txtunidadentrada.getText();
    }

    public void setTxtunidadentrada(String txtmonedaentrada) {
        this.txtunidadentrada.setText(txtmonedaentrada);
    }

    public String getTxtunidadsalida() {
        return txtunidadsalida.getText();
    }

    public void setTxtunidadsalida(String txtmonedasalida) {
        this.txtunidadsalida.setText(txtmonedasalida);
    }

    public int getCbunidadentrada() {
        return cbunidadentrada.getSelectedIndex();
    }

    public int getCbunidadsalida() {
        return cbunidadsalida.getSelectedIndex();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSComboBox cbunidadentrada;
    private rojerusan.RSComboBox cbunidadsalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private RSMaterialComponent.RSButtonIconUno rSButtonIconUno1;
    private RSMaterialComponent.RSTextFieldMaterialIcon txtunidadentrada;
    private RSMaterialComponent.RSTextFieldMaterialIcon txtunidadsalida;
    // End of variables declaration//GEN-END:variables

}
