/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package conversor.de.monedas;

import RSMaterialComponent.RSTextFieldMaterialIcon;
//import static conversor.de.monedas.Convertidor.getCbmonedaentrada;
import java.text.DecimalFormat;
import rojerusan.RSComboBox;

/**
 *
 * @author santiago
 */
public class Convertidor extends javax.swing.JFrame {
    
    
    /**
     * Creates new form Convertidor 
     */
  
       

 
       
      
    
    
    
    public Convertidor() {
        initComponents();
       

       
        
       
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbmonedaentrada = new rojerusan.RSComboBox();
        txtmonedaentrada = new RSMaterialComponent.RSTextFieldMaterialIcon();
        cbmonedasalida = new rojerusan.RSComboBox();
        txtmonedasalida = new RSMaterialComponent.RSTextFieldMaterialIcon();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 204, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CONVERTIDOR DE MONEDAS");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 310, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 50));

        cbmonedaentrada.setBackground(new java.awt.Color(255, 204, 51));
        cbmonedaentrada.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ELIJA MONEDA", "Sol Peruano PEN", "Dolar USD", "Euro EUR", "Libra Esterlina GBP", "Yen Japones  JPY", "Won Sul-Coreano KRW" }));
        cbmonedaentrada.setColorArrow(new java.awt.Color(255, 204, 51));
        cbmonedaentrada.setColorBorde(new java.awt.Color(255, 255, 0));
        cbmonedaentrada.setColorFondo(new java.awt.Color(255, 204, 51));
        cbmonedaentrada.setColorSeleccion(new java.awt.Color(255, 204, 51));
        cbmonedaentrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbmonedaentradaMousePressed(evt);
            }
        });
        jPanel1.add(cbmonedaentrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 40));

        txtmonedaentrada.setForeground(new java.awt.Color(255, 204, 51));
        txtmonedaentrada.setText("0");
        txtmonedaentrada.setColorIcon(new java.awt.Color(255, 204, 51));
        txtmonedaentrada.setColorMaterial(new java.awt.Color(255, 204, 51));
        txtmonedaentrada.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.MONETIZATION_ON);
        txtmonedaentrada.setPhColor(new java.awt.Color(0, 0, 0));
        txtmonedaentrada.setPlaceholder("Escribir aqui");
        txtmonedaentrada.setSelectionColor(new java.awt.Color(255, 204, 51));
        txtmonedaentrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmonedaentradaActionPerformed(evt);
            }
        });
        txtmonedaentrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmonedaentradaKeyReleased(evt);
            }
        });
        jPanel1.add(txtmonedaentrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 150, -1));

        cbmonedasalida.setBackground(new java.awt.Color(255, 204, 51));
        cbmonedasalida.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ELIJA MONEDA", "Sol Peruano PEN", "Dolar USD", "Euro EUR", "Libra Esterlina GBP", "Yen Japones  JPY", "Won Sul-Coreano KRW" }));
        cbmonedasalida.setColorArrow(new java.awt.Color(255, 204, 51));
        cbmonedasalida.setColorBorde(new java.awt.Color(255, 255, 0));
        cbmonedasalida.setColorFondo(new java.awt.Color(255, 204, 51));
        cbmonedasalida.setColorSeleccion(new java.awt.Color(255, 204, 51));
        jPanel1.add(cbmonedasalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, 40));

        txtmonedasalida.setForeground(new java.awt.Color(255, 204, 51));
        txtmonedasalida.setText("0");
        txtmonedasalida.setToolTipText("");
        txtmonedasalida.setColorIcon(new java.awt.Color(255, 204, 51));
        txtmonedasalida.setColorMaterial(new java.awt.Color(255, 204, 51));
        txtmonedasalida.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.MONETIZATION_ON);
        txtmonedasalida.setPhColor(new java.awt.Color(0, 0, 0));
        txtmonedasalida.setPlaceholder("Escribir aqui");
        txtmonedasalida.setSelectionColor(new java.awt.Color(255, 204, 51));
        txtmonedasalida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmonedasalidaKeyReleased(evt);
            }
        });
        jPanel1.add(txtmonedasalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 150, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtmonedaentradaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmonedaentradaKeyReleased
         
        conversorsuperior cs= new conversorsuperior();

        if(txtmonedaentrada.getText().equals("")||txtmonedasalida.getText().equals("")){
         txtmonedaentrada.setText("0");
         txtmonedasalida.setText("0");
         }else{
            System.out.println("obteniendo combo1"+getCbmonedaentrada());
            if (getCbmonedaentrada()== 1) {
                System.out.println(getCbmonedaentrada());
                System.out.println(this.getTxtmonedaentrada());
                 this.txtmonedasalida.setText(cs.conversorPENaTODOS(this.getTxtmonedaentrada(),this.getCbmonedasalida()));
                System.out.println("convesor"+this.getTxtmonedasalida());
            }
            if (cbmonedaentrada.getSelectedIndex() == 2) {
        // cs.conversorUSDaTODOS();
            }
            if (this.cbmonedaentrada.getSelectedIndex() == 3) {
         // cs.conversorEURaTODOS();
            }
            if (this.cbmonedaentrada.getSelectedIndex() == 4) {
       // cs.conversorGBPaTODOS();
            }
            if (this.cbmonedaentrada.getSelectedIndex() == 5) {
         //cs.conversorJPYaTODOS();
            }
            if (this.cbmonedaentrada.getSelectedIndex() == 6) {
        //cs.conversorKRWaTODOS();
            }
            
            
      
      
        
       
        
        
                 }
    }//GEN-LAST:event_txtmonedaentradaKeyReleased

    private void txtmonedaentradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmonedaentradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmonedaentradaActionPerformed

    private void txtmonedasalidaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmonedasalidaKeyReleased
        // TODO add your handling code here:
        
            if(txtmonedaentrada.getText().equals("")||txtmonedasalida.getText().equals("")){
         txtmonedaentrada.setText("0");
         txtmonedasalida.setText("0");
         }else{
        
        
       // double me= Double.parseDouble(this.txtmoedaentrada.getText());
        double ms=Double.parseDouble(txtmonedasalida.getText());
        
       
       
        
       
                
        if(this.cbmonedaentrada.getSelectedIndex()==1){
            if(this.cbmonedasalida.getSelectedIndex()==2){
                
                // double sd= me*0.26404034536477173712143215483326;
               // this.txtmonedasalida.setText(String.valueOf(sd));
                
                 double ds= ms*3.7873;
                 double dsr= Math.round(ds*10000.0)/10000.0;
                this.txtmonedaentrada.setText(String.valueOf(dsr));
            }
           
            }
            
            
        }
            
    }//GEN-LAST:event_txtmonedasalidaKeyReleased

    private void cbmonedaentradaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbmonedaentradaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbmonedaentradaMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Convertidor().setVisible(true);
            }
        });
    }
    
    public String getTxtmonedaentrada() {
        return txtmonedaentrada.getText();
    }

    public void setTxtmonedaentrada(String txtmonedaentrada) {
        this.txtmonedaentrada.setText(txtmonedaentrada);
    }

    public String getTxtmonedasalida() {
        return txtmonedasalida.getText();
    }

    public void setTxtmonedasalida(String txtmonedasalida) {
        this.txtmonedasalida.setText(txtmonedasalida);
    }

    public  int getCbmonedaentrada() {
        return cbmonedaentrada.getSelectedIndex();
    }

    public  int getCbmonedasalida() {
        return cbmonedasalida.getSelectedIndex();
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSComboBox cbmonedaentrada;
    private rojerusan.RSComboBox cbmonedasalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private RSMaterialComponent.RSTextFieldMaterialIcon txtmonedaentrada;
    private RSMaterialComponent.RSTextFieldMaterialIcon txtmonedasalida;
    // End of variables declaration//GEN-END:variables






}
